// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VCD2WrN5Wb6DHyw2BpFUFCK6n_QOZDQ',
    appId: '1:997706105988:web:efaabae8c20d6e584eeed1',
    messagingSenderId: '997706105988',
    projectId: 'timeit-104e5',
    authDomain: 'timeit-104e5.firebaseapp.com',
    storageBucket: 'timeit-104e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQLkyKAU_Jqli8t9hrzrzwfzmLkaxp9U',
    appId: '1:997706105988:android:2907cee1aa581d5c4eeed1',
    messagingSenderId: '997706105988',
    projectId: 'timeit-104e5',
    storageBucket: 'timeit-104e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZtjIhIVcy5dyCQnfPFC-n5wrVNmZhqA',
    appId: '1:997706105988:ios:ef722e1b14f9f3254eeed1',
    messagingSenderId: '997706105988',
    projectId: 'timeit-104e5',
    storageBucket: 'timeit-104e5.appspot.com',
    iosClientId: '997706105988-n714ugurr9t87l0kgo49dhubv80a1i67.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZtjIhIVcy5dyCQnfPFC-n5wrVNmZhqA',
    appId: '1:997706105988:ios:ef722e1b14f9f3254eeed1',
    messagingSenderId: '997706105988',
    projectId: 'timeit-104e5',
    storageBucket: 'timeit-104e5.appspot.com',
    iosClientId: '997706105988-n714ugurr9t87l0kgo49dhubv80a1i67.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeit',
  );
}
